name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
     - uses: actions/setup-node@v4
  with:
    node-version: '20.19.0'

- name: Build app
  run: npm run build

- name: Deploy to Azure Static Web Apps
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    action: upload
    skip_app_build: true
    app_location: /
    app_artifact_location: out   # <-- must match your Vite outDir
      
